# Generated by Django 4.2.1 on 2023-05-18 08:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_staff_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Author',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Date_Posted',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='Title',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='facebook',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='img_File',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='staff',
            name='instagram',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='linkedIn',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='staff',
            name='twitter',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog.categories'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_posted',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
