# Generated by Django 4.2.1 on 2023-05-18 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_login_remove_blogpost_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='content_short',
            field=models.CharField(default='', max_length=100),
        ),
    ]
