# Generated by Django 4.2.1 on 2023-05-18 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogpost_content_short'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='content_short',
        ),
    ]
