# Generated by Django 4.2.1 on 2023-05-18 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blogpost_content_short'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='OpportunityPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.FileField(upload_to='')),
                ('title', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=100)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.opportunity')),
            ],
        ),
    ]
