# Generated by Django 4.2.1 on 2023-05-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_opportunity_opportunitypost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitypost',
            name='background',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
