# Generated by Django 4.2.1 on 2023-05-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_opportunitypost_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemesJokes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.FileField(blank=True, null=True, upload_to='')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
