# Generated by Django 4.2.1 on 2023-05-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_event_alter_blogpost_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MorJ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
