# Generated by Django 4.2.1 on 2023-05-18 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_morj'),
    ]

    operations = [
        migrations.AddField(
            model_name='memesjokes',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.morj'),
        ),
        migrations.AlterField(
            model_name='memesjokes',
            name='content',
            field=models.CharField(default='', max_length=100),
        ),
    ]
