# Generated by Django 4.2.1 on 2023-05-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_memesjokes_category_alter_memesjokes_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memesjokes',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
