# Generated by Django 4.2.1 on 2023-05-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_opportunitypost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunitypost',
            name='title',
            field=models.CharField(default='', max_length=30),
        ),
    ]
